import tkinter as tk
root =tk.Tk()
root.geometry("600x300")
root.title("TKInter tutorial")
frame1 = tk.Frame(root)

frame1.columnconfigure(0, weight=1)
frame1.columnconfigure(1, weight=1)
frame1.columnconfigure(2, weight=1)
frame1.rowconfigure(0, weight=1)
frame1.rowconfigure(1, weight=1)

button1 = tk.Button(frame1, text="Click me")
button1.grid(row=0,column=0, sticky="nsew")
button2 = tk.Button(frame1, text="Click me")
button2.grid(row=0,column=1,sticky="nsew")
button3 = tk.Button(frame1, text="Click me")
button3.grid(row=0,column=2,sticky="nsew")
button4 = tk.Button(frame1, text="Click me")
button4.grid(row=1,column=0,sticky="nsew")
button5 = tk.Button(frame1, text="Click me")
button5.grid(row=1,column=1,sticky="nsew")
button6 = tk.Button(frame1, text="Click me")
button6.grid(row=1,column=2,sticky="nsew")
root.rowconfigure(0, weight=1)
root.rowconfigure(1, weight=1)
root.columnconfigure(0,weight=1)
frame1.grid(row=0,column=0,sticky="nsew")
button7 = tk.Button(text="special button")
button7.grid(row=1,column=0)
root.mainloop()
